import Vue from "vue";

import Button from "./Button.vue";
import Card from "./Card.vue";
import Container from "./Container.vue";
import Row from "./Row.vue";
import Col from "./Col.vue";
import Flexbox from "./Flexbox.vue";
import Tooltip from "./Tooltip.vue";
import Navbar from "./Navbar.vue";
import Image from "./LazyImage.vue";
import Footer from "./Footer.vue";
import Icon from "./Icon.vue";
import SocialMediaLinks from "./SocialMediaLinks.vue";
import FullScreenOverlay from "./FullScreenOverlay.vue";
import CVButton from "./CVButton.vue";
import ToolboxItem from "./ToolboxItem.vue";

Vue.component("bou-button", Button);
Vue.component("bou-cv-button", CVButton);
Vue.component("bou-card", Card);
Vue.component("bou-container", Container);
Vue.component("bou-row", Row);
Vue.component("bou-col", Col);
Vue.component("bou-flexbox", Flexbox);
Vue.component("bou-tooltip", Tooltip);
Vue.component("bou-navbar", Navbar);
Vue.component("bou-image", Image);
Vue.component("bou-footer", Footer);
Vue.component("bou-icon", Icon);
Vue.component("bou-social-media-links", SocialMediaLinks);
Vue.component("bou-full-screen-overlay", FullScreenOverlay);
Vue.component("bou-toolbox-item", ToolboxItem);
